In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 5 6]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.25.2


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [35]:
arr0 = np.array(25)
print(arr0)
print(arr0.ndim)

25
0


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [6]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5 6]
1


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

***These are often used to represent matrix or 2nd order tensors.***

***NumPy has a whole sub module dedicated towards matrix operations called numpy.mat***

In [33]:
arr2 = np.array([[1,2,3],[1,3,3]])
print(arr2)
print(arr2.ndim)

print(arr2[0] + arr2[1])

[[1 2 3]
 [1 3 3]]
2
[2 5 6]


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

***These are often used to represent a 3rd order tensor.***

In [32]:
arr3 = np.array([[[12,3,4],[1,4,6],[3,4,5]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.ndim)

print(arr3[0] + arr3[1])

[[[12  3  4]
  [ 1  4  6]
  [ 3  4  5]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
3
[[13  5  7]
 [ 5  9 12]
 [10 12 14]]


Higher Dimensional Arrays
An array can have any number of dimensions.
***When the array is created, you can define the number of dimensions by using the ndmin argument.***

In [9]:
arr_mul = np.array([1,2,3,4,5], ndmin=5)
print(arr_mul)

print('nuber of dimension : ', arr_mul.ndim)

[[[[[1 2 3 4 5]]]]]
nuber of dimension :  5


***In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.***


# NumPy Array Indexing

In [10]:
print(arr[2] + arr[3])


7


# Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [20]:
arr2 = np.array([[1,2,3],[5,4,7]])
print(arr2)
print(arr2[1,2])
print(arr2[1,-2])

[[1 2 3]
 [5 4 7]]
7
4


# Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [15]:
import numpy as np

arr3_index = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3_index[0, 1, 2])

6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]
and:

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:

[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two
arrays:

[1, 2, 3]

and:

[4, 5, 6]

Since we selected 1, we are left with the second array:

[4, 5, 6]

The third number represents the third dimension, which contains three values:

4
5
6

Since we selected 2, we end up with the third value:

6

In [19]:
print(arr3_index)
print(arr3_index[1,-2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[7 8 9]


# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

 If we don't pass step its considered 1

In [38]:
arr_s = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr_s[1:5])
print(arr_s[1:])
print(arr_s[:3])


[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3]


Note: The result includes the start index, but excludes the end index.

# Negative Slicing
Use the minus operator to refer to an index from the end:

Example
Slice from the index 3 from the end to index 1 from the end:

In [40]:
print(arr_s[-3:-1])  #not include -1

[5 6]


# STEP
Use the step value to determine the step of the slicing:

Example
Return every other element from index 1 to index 5:

In [53]:
arr_st = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr_st[1:5:2])
# Return every other element from the entire array:
print(arr_st[::2])

print(arr_st[::3])




[2 4]
[1 3 5 7]
[1 4 7]


# Slicing 2-D Arrays
Example
From the second element, slice elements from index 1 to index 4 (not included):

In [48]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4]) # 1 show column 1

print(arr[0,1:4]) #0 shows col 1
# here just 1 row

[7 8 9]
[2 3 4]


From both elements, return index 2:

In [50]:
print(arr[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [54]:
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [56]:
print(arr[0,1:4])  # from 0 indexed column

[2 3 4]


In [61]:
print(arr[1,1:4])   # from 1 indexed column

[7 8 9]


In [62]:
print(arr[0:2, 2])

[3 8]


In [65]:
print(arr[0:2, 2:5])

[[ 3  4  5]
 [ 8  9 10]]
